language: node_js

node_js: latest

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g
    - chmod +x ./deploy.sh

install:
    - npm install

script:
    - hexo clean
    - hexo g >/dev/null 2>&1

after_script:
    - ./deploy.sh

branches:
    only:
        - master

env:
    global:
        - CodingRepo: e.coding.net/yuangezhizao/yuangezhizao.git
